### ISSUE TITLE
[ENHANCEMENT] Identify widgets separately in analytics 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#464] opened 2021-09-30 14:50 UTC
Enhance analytics to separate "m2m", "widgets", "bots" and "users" for a better breakdown of API calls in PxStat

**Comment by neilfromcork** [comment] 2021-11-04 12:15
Server side completed

**Comment by JohnPCarroll** [comment] 2022-03-31 11:21
Duplicate of #466

**Closed by JohnPCarroll** 2022-03-31 11:21 UTC
Labels: enhancement
