### ISSUE TITLE
[BUG] Link in px file notes is missing when downloaded in Data page

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#303] opened 2020-11-24 11:46 UTC
**Describe the bug**
The URL link is removed from the PX file when downloaded in the data page. Table used BGA04

**Expected behavior**
Link details should be retained.

**Screenshots**
Source download
![image](https://user-images.githubusercontent.com/44975474/100089961-66acf280-2e4a-11eb-93e0-fc90ddf04941.png)

Data page download
![image](https://user-images.githubusercontent.com/44975474/100090062-86441b00-2e4a-11eb-879c-92124b8f9a81.png)

**Comment by neilfromcork** [comment] 2020-11-24 16:20
Fixed in DEV - ready for test. Returns html version for JSON-stat and XLSX, bbcode for everything else.

**Comment by lorenzobruni** [comment] 2020-11-27 11:20
@neilfromcork look at Open XML for inserting hyperlinks

**Comment by lorenzobruni** [comment] 2020-11-27 11:25
Duplicate of #300

**Closed by lorenzobruni** 2020-11-27 11:25 UTC
Labels: bug, duplicate

**Comment by neilfromcork** [comment] 2020-11-27 15:46
Amended on XLSX files to show url's as clickable formatted links. Note that this is not applied to the RESTful url of the excel file itself. Clicking on such a link would just download another copy of the same XLSX file.
