### ISSUE TITLE
[BUG] After using database reorganise update navigation in release returns to database screen not releases

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#390] opened 2021-03-16 14:46 UTC
**Describe the bug**
After using database reorganise update navigation in release returns to database screen not releases

**To Reproduce**
1. Go to Database
2. Click on Reorganise 
3. after confirmation 
4. Go to any release, update navigation 
5. After Save and Close Database window reappears not release

**Expected behavior**
Release window should reappear

This occurs if either individual table or reorganise all button is used at step 2

**Comment by liamie** [comment] 2021-03-16 15:05
This also impacts on import -> validation when click close on success modal

**Comment by liamie** [comment] 2021-03-16 15:12
Adding keyword, product etc. also impacted, seems to be anything with this dialog.
![image](https://user-images.githubusercontent.com/55874862/111332727-f2e95c80-8669-11eb-8bc4-5002a2d60cc2.png)

**Comment by damienderoistecso** [comment] 2021-03-16 16:22
Going to mark this as a Duplicate of #384 as it's not a fresh bug but rather associated with this enhancement.

**Closed by damienderoistecso** 2021-03-16 16:22 UTC
Labels: bug, duplicate
