### ISSUE TITLE
[BUG] Error during Build parse for file with no timeval

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#199] opened 2020-09-02 08:07 UTC
If you try to parse a px file with no timeval in BUILD, an error occurs.
The client calls 2 APIs for this - PxStat.Build.Build_API.Validate and PxStat.Build.Build_API.Read. 

The Validate sends back a list of dimensions for the user to choose from as time dimensions. However it looks like the Read goes ahead before this choice can be made. This leads to an error due to there being no time dimension in the matrix.

**Comment by neilfromcork** [comment] 2020-09-03 09:18
Fixed- ready for test @damienderoistecso

**Comment by damienderoistecso** [comment] 2020-09-03 10:07
This issue arose from #183

**Comment by damienderoistecso** [comment] 2020-09-03 13:05
Duplicate of #183 

@JohnPCarroll @liamie can you test to make sure we can now upload a px file without a timeval in import, create/import and update

**Comment by liamie** [comment] 2020-09-03 13:24
This worked correctly for me in create, update and build with file EQQ02.px

**Closed** 2020-09-03 13:45 UTC
Labels: bug, duplicate, fixed, tested
