### ISSUE TITLE
[BUG] Error with build update

### ISSUE THREAD

**Issue by 1556953** [CSOIreland/PxStat#59] opened 2020-01-28 09:21 UTC
I receive an unclear error message when uploading data.

**To Reproduce**
1. Go to 'build' - update
[CEN1.20200124T160145.txt](https://github.com/CSOIreland/PxStat/files/4121553/CEN1.20200124T160145.txt)

upload PX file
upload data file

[CEN1.20200124T150152.template.txt](https://github.com/CSOIreland/PxStat/files/4121574/CEN1.20200124T150152.template.txt)

error message received
![image](https://user-images.githubusercontent.com/60383775/73250745-5c30b680-41af-11ea-82df-a551065d36ca.png)

**Comment by 1556953** [comment] 2020-01-28 17:27
Similarly with build - update
[CEN1.20200128T160129.txt](https://github.com/CSOIreland/PxStat/files/4123703/CEN1.20200128T160129.txt)
upload data file
[CEN1.20200124T150152.template.txt](https://github.com/CSOIreland/PxStat/files/4123711/CEN1.20200124T150152.template.txt)

I receive the following error 
![image](https://user-images.githubusercontent.com/60383775/73288742-71c7cf80-41f3-11ea-994d-4cdf03c64cb5.png)

**Comment by neilfromcork** [comment] 2020-03-05 13:58
The original csv file had entries for Age Group 12. This age group is not represented in the px file, hence the error. I regenerated the csv file from the application but this time there were no entries for Age Group 12 and the update occurred without problems. Can you give me more information about what happened?

**Comment by neilfromcork** [comment] 2020-03-19 18:08
Refactoring to (a) return a validation issue rather than an error when invalid data is sent, and (b) return more specific details of how the data was invalid.

**Comment by neilfromcork** [comment] 2020-03-24 09:18
Ready for retest @JohnPCarroll @liamie

**Comment by neilfromcork** [comment] 2020-03-24 09:21
The original files will (correctly) fail to update. However the validation error should be much more informative

**Comment by liamie** [comment] 2020-03-26 15:25
Validation error much clearer.
No variables found for item Classifications:Age Group 12
However this seems to repeat for each occurrence I believe and so the error box is quite long and presumably would be longer if more lines had missing classifications or multiple classifications missing.
![image](https://user-images.githubusercontent.com/55874862/77663854-6e439100-6f75-11ea-9d39-06675786423a.png)

Would it be possible to have it inform the error or errors X number of occurrences
eg. No variables found for item Classifications:Age Group 12  (25)

**Comment by damienderoistecso** [comment] 2020-04-07 10:01
Duplicate of #114

**Closed by damienderoistecso** 2020-04-07 10:01 UTC
Labels: bug, duplicate
