### ISSUE TITLE
Ability to sort Periods/Statistics/Classifications in Create

### ISSUE THREAD

**Issue by carolfinlay** [CSOIreland/PxStat#349] opened 2021-01-20 15:32 UTC
When you need to re-order new period/statistic/classification in the create option you currently have to delete the entire entries and re-input them in the new order.  Can we please have the ability to re-order (drag and drop) in the create.

**Comment by lorenzobruni** [comment] 2021-02-10 15:07
@damienderoistecso to review together

**Comment by lorenzobruni** [comment] 2021-02-19 09:37
Work on this together with #350

**Comment by lorenzobruni** [comment] 2021-04-19 09:02
Duplicate of #350

**Closed by lorenzobruni** 2021-04-19 09:02 UTC
Labels: enhancement
