### ISSUE TITLE
[BUG] On Data page clicking on Links in Note required you to leave the application to view them. 

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#342] opened 2021-01-06 09:31 UTC
**Describe the bug**
See Data Page. Table used BHA06. When you click on the link in Note you must leave the application. This is incorrect as you should get a new tab where the details are displayed.

**To Reproduce**
1. Go to Data 
2. Enter in Table Code BHA06
3. Click on table to view details
4. Click on Link See Background Notes
5.  You must select leave to view them. 

**Expected behavior**
When you click on the link See Background notes a new tab should appear with the details. It should behave in the same way as the Public Comment Link 

**Screenshots**
Footnote
![image](https://user-images.githubusercontent.com/44975474/103752216-54a1a080-5001-11eb-9be7-eb1bbfb23189.png)

Public Comments 
![image](https://user-images.githubusercontent.com/44975474/103752475-ac400c00-5001-11eb-97e7-2095a0237656.png)

**Comment by lorenzobruni** [comment] 2021-02-10 15:22
@damienderoistecso add target blank to the BBCode parser

**Comment by lorenzobruni** [comment] 2021-02-10 15:40
@damienderoistecso Client should always parse the BBCode, which apparently is the case. Please verify.
@neilfromcork Server should store Notes as they are, because is source data. The only exception is about stripping HTML in the sanitization. As result, a note may contain only pure text with maybe BBCode to be stored into the DB.
When read form the DB, then it can be parsed for viewing purposes, like XLSX or eMails.
JSON-stat outputs should be transparent, because we cannot assume how the client will be suing the output, so no BBCode parsing form the server.

**Comment by lorenzobruni** [comment] 2021-02-15 11:59
@neilfromcork could you remove the BBCode parser for JSON-stat and write a script to fix the DB entries? Thanks

**Comment by lorenzobruni** [comment] 2021-02-16 11:00
Duplicate of #368

**Closed by lorenzobruni** 2021-02-16 11:00 UTC
Labels: bug
