### ISSUE TITLE
[BUG] Compare release can not complete correctly if moderator is not in relevant groups for the Matrix

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#388] opened 2021-03-08 15:07 UTC
**Describe the bug**
A matrix was loaded to group 1 and it went live. When loaded the next time it was assigned to another group.  
If the moderator approver selects the Compare Release button it will not work correctly as the release in group 1 is not available to the moderator.

**Comment by lorenzobruni** [comment] 2021-04-12 13:23
@damienderoistecso 
Might be the issue is when checking if a previous release exists... maybe the check doe snot consider the Group of the previous release? Please liaise with @neilfromcork

**Comment by damienderoistecso** [comment] 2021-04-13 11:31
@neilfromcork "PxStat.Data.Compare_API.ReadPreviousRelease" is only used on the client for the purposes of determining whether the user has a previous release to run the comparison report against. Maybe this API could be modified on the server to only return any previous release they are entitled to know about rather than the current logic of any previous release regardless of it's group

**Comment by neilfromcork** [comment] 2021-04-15 08:03
Fixed in DEV - ready for test. User should not be able to detect a previous release if they haven't got rights to it.

**Comment by damienderoistecso** [comment] 2021-04-15 10:07
@neilfromcork can you look into this #411

**Comment by neilfromcork** [comment] 2021-04-15 10:08
Fixed in DEV - Ready for test @damienderoistecso @JohnPCarroll

**Comment by JohnPCarroll** [comment] 2021-04-15 11:21
Test Passed for Comparing reports. If you are not a member of Group 1 the button is not active. When you are a member of both groups the button is active.

**Comment by damienderoistecso** [comment] 2021-04-15 11:47
@JohnPCarroll Can you check if the issue with deleting the release is resolved also

**Comment by JohnPCarroll** [comment] 2021-04-15 13:05
Test passed for Delete signoff.

**Closed** 2021-04-19 22:27 UTC
Labels: bug, fixed, released, tested
