### ISSUE TITLE
[ENHANCEMENT] Normalize Excel library for handling XLSX file creation

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#171] opened 2020-04-09 12:04 UTC
Create API library for Excel creation

**Comment by lorenzobruni** [comment] 2020-07-27 17:23
@neilfromcork 
This one was incorrectly created under the wrong repo `Server-API-Library`.
I transfer it here.

If I remember well this was already implemented and tested, correct? 
Thanks

**Comment by neilfromcork** [comment] 2020-07-27 18:08
Yes. This seems to be a duplicate of #128

**Comment by lorenzobruni** [comment] 2020-07-28 19:21
Perfect, thanks!
Duplicate of #128

**Closed by lorenzobruni** 2020-07-28 19:21 UTC
Labels: duplicate, enhancement
