### ISSUE TITLE
[ENHANCEMENT] Replace Read CSV APIs in Build with one API

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#205] opened 2020-09-03 17:18 UTC
Allow users to view CSV Build data based on:
- One period
- Several periods
- All periods

Also allow users to choose whether or not labels are to  be shown in the CSV output

**Comment by damienderoistecso** [comment] 2020-09-04 09:22
Duplicate of #204

**Closed** 2020-09-04 09:22 UTC
Labels: duplicate, enhancement
