### ISSUE TITLE
New published items now give error when accessed

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#402] opened 2021-03-31 11:12 UTC
New published items now give error when accessed 
On Data Page
Last updated tables click a table published today 31/03 error occurs
![image](https://user-images.githubusercontent.com/55874862/113131054-9fa00e00-9214-11eb-9e4f-d001a0e8a95d.png)

**Comment by liamie** [comment] 2021-03-31 11:30
Also occurs when trying to view gaeilge option on second language files on release page when change the source isection to gaeilge and click view data
![image](https://user-images.githubusercontent.com/55874862/113137485-813e1080-921c-11eb-91c4-e02902344be5.png)

**Comment by neilfromcork** [comment] 2021-03-31 11:34
Temporary problem caused by ELIMINATION change. Currently resolved. Will be permanently resolved when elimination is added to upload

**Comment by damienderoistecso** [comment] 2021-03-31 11:38
Duplicate of #395

**Closed by damienderoistecso** 2021-03-31 11:38 UTC
Labels: bug, duplicate
