### ISSUE TITLE
Data page Navigation tree overlaying Latest Releases[BUG] 

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#130] opened 2020-05-13 11:44 UTC
I had PXstat open in Chrome on the Data page. I shrunk the Chrome window and the Navigation tree on the right under Browse didn't resize and overlayed the Latest Releases.
Screenshot attached
![PXStat Bug](https://user-images.githubusercontent.com/59689411/81808235-5325e400-9517-11ea-951c-7f1c59f71b47.PNG)

**Comment by damienderoistecso** [comment] 2020-05-19 08:16
Duplicate of #129

**Closed by damienderoistecso** 2020-05-19 08:16 UTC
Labels: duplicate
