### ISSUE TITLE
[BUG] Build Create Import gives unexpected error rather than inform issues

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#613] opened 2022-08-08 13:57 UTC
**Describe the bug**
Build Create Import gives unexpected error rather than inform issues.

**To Reproduce**
1. Go to 'Build'
2. Click on 'Create '
3. Click on  'Import File'
4. Parse a file with an error
5. See message about un expected error

**Expected behavior**
The issues causing the error should be listed similar to Build Import on Dev or Existing Live or Build >Create> Import on existing Live

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/183435208-08b09ee9-2e22-4836-8a4d-ae20380988ff.png)

![image](https://user-images.githubusercontent.com/55874862/183434547-413ffb9a-d22c-4b9b-ad64-72aa83fa770e.png)

**Comment by damiancosmoschapman** [comment] 2022-08-09 07:53
I've added a fix for this issue now. The bug was caused by my missing of some references to the old parser. These references are fixed now. Please retest when you get a chance and let me know if you find any issues.

**Comment by damiancosmoschapman** [comment] 2022-08-10 11:02
*This issue is fixed now. Please retest when you get a chance and let me know if you find any issues.

**Comment by liamie** [comment] 2022-08-11 11:27
This seems to be corrected now and matches current live

**Closed** 2023-01-12 15:30 UTC
Labels: bug, released, tested, fixed
