### ISSUE TITLE
[BUG] ReadCollection failing to write to cache

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#136] opened 2020-05-21 09:14 UTC
The Read Collection API isn't writing to the cache and causing slow performance when a large number of tables are stored.

**Comment by neilfromcork** [comment] 2020-05-21 09:14
Bug fixed - ready for test.

**Comment by damienderoistecso** [comment] 2020-05-28 15:34
Duplicate of #138

**Closed by damienderoistecso** 2020-05-28 15:34 UTC
Labels: bug, duplicate, fixed
