### ISSUE TITLE
[ENHANCEMENT] Remove create option in the build for moderators

### ISSUE THREAD

**Issue by carolfinlay** [CSOIreland/PxStat#96] opened 2020-03-05 10:16 UTC
We do not currently want moderators to be able to use the create option in PXBuild.  Can this please be automatically off but have it so that we can toggle it on if we wish (like making a moderator an approver).

Thanks

Carol

**Comment by lorenzobruni** [comment] 2020-03-09 16:46
Hi, we are looking into it, discussing feasibility. 

What is the main reason behind this change request, considering that **PX** is a public text format that everybody can anyway easily create from scratch, either using public software like `PcAxis`, `PxMake`, `PxEdit `or programming languages like `SAS`, `R` or simply with any text editor?

Is this to facilitate an **Office Policy** perhaps?

Thanks

**Comment by lorenzobruni** [comment] 2020-04-09 12:13
Following internal PM this issue has been escalated to be implemented under the configuration change.
This would allow to set the access to the Build (Create, Update, Import) by Privilege via the configuration settings.

**Comment by lorenzobruni** [comment] 2020-04-09 12:14
Duplicate of #123

**Closed by lorenzobruni** 2020-04-09 12:14 UTC
Labels: enhancement
