### ISSUE TITLE
[ENHANCEMENT] Allow pivoting of table results in the data entity 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#167] opened 2020-07-20 09:46 UTC
Add pivot option for data results in data entity

![image](https://user-images.githubusercontent.com/53211688/87923858-03631c00-ca76-11ea-8b6f-7d6ee2a912dc.png)

**Comment by liamie** [comment] 2020-07-22 10:09
Unusual behavior in pivot VSA50
I choose one statistic and one year with 603 names due to volume messages if picking very high numbers
 when I pivoted by name in addition to the one correct line expected multiple lines with blank info appeared
![image](https://user-images.githubusercontent.com/55874862/88163969-591cfd00-cc0b-11ea-848d-910745a093c5.png)

**Comment by lorenzobruni** [comment] 2020-07-23 11:39
@liamie thanks for the full report, it was very useful for me to reproduce the issue and identify the problem.
The issue is fixed by checking if the `value `property exists rather than checking it's actual content. This was causing an issue confusing between  0 (zero), NULL and non-existing.

Please run an update and test again, thanks!

**Comment by liamie** [comment] 2020-07-23 13:06
This seems to be correct now

**Comment by liamie** [comment] 2020-07-23 13:34
Statistical indicator is not listed as one of the pivot options in the dropdown.
It is in StatBank.

**Comment by lorenzobruni** [comment] 2020-07-27 19:56
Good spot Liam,  please find it fixed.

@JohnPCarroll can you please test that the Statistic is now available into the Pivot option dropdown while Liam is out of office? Thanks

See example attached below
![image](https://user-images.githubusercontent.com/53212047/88585942-ac4be100-d04b-11ea-9594-41aebc066c05.png)

**Closed** 2020-07-31 22:19 UTC
Labels: enhancement, fixed, released, tested
