### ISSUE TITLE
[BUG] view data hanging in releases in progress screen

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#156] opened 2020-07-03 13:23 UTC
when trying to view data in the releases (work in progress)
1. go to the work in progress page of a release
2. click on 'view data' button

rather than displaying data hangs on this screen

![image](https://user-images.githubusercontent.com/55874862/86473351-a9a1e880-bd38-11ea-9c9d-e2c0a8b0fc85.png)

**Comment by neilfromcork** [comment] 2020-07-03 14:45
Seems ok in 2.3 - front end needs to be checked. @damienderoistecso

**Comment by damienderoistecso** [comment] 2020-07-03 15:31
Side affect of #149

**Comment by damienderoistecso** [comment] 2020-07-20 09:24
Duplicate of #165

**Comment by damienderoistecso** [comment] 2020-07-20 09:25
Duplicate of #165

**Closed by damienderoistecso** 2020-07-20 09:25 UTC
Labels: duplicate, invalid
