### ISSUE TITLE
[BUG] The last entry of pivoted excel and csv datasets contain a duplicate of the second last line

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#327] opened 2020-12-08 17:26 UTC
In some circumstances, the last entry of pivoted excel and csv datasets contain a duplicate of the second last line rather than the last data item

**Comment by JohnPCarroll** [comment] 2020-12-09 09:42
Test passed. Used all types of Pivot dropdown options.

**Comment by liamie** [comment] 2020-12-09 15:23
Front end pivot row counts now do not match downloaded csv/xls row count

![image](https://user-images.githubusercontent.com/55874862/101648005-4c216e80-3a31-11eb-9c1a-cc11a540f15c.png)

however the csv and xls have a row count of 96 (97-1 for title row) for the same pivot which I think is correct for the same pivot 

I think this is occurring on even numbered classifications chosen

**Comment by JohnPCarroll** [comment] 2020-12-09 15:33
Liam,
	Is that error in Live or Dev only ?

Regards

John Carroll
Higher Executive Officer/Systems Analyst
Technology Dissemination
Email john.carroll@cso.ie
Telephone 021 4535630
Subject to the disclaimer at http://www.cso.ie/en/emaildisclaimer/ Faoi r�ir ag an s�anadh ag http://www.cso.ie/en/seanadhriomhphoist/

**Comment by lorenzobruni** [comment] 2021-02-10 16:23
Duplicate of #328

**Closed by lorenzobruni** 2021-02-10 16:23 UTC
Labels: bug, fixed, tested
