### ISSUE TITLE
[BUG] Compare not running for a particular table

### ISSUE THREAD

**Issue by DeclanBuckley** [CSOIreland/PxStat#640] opened 2022-09-20 10:14 UTC
I am getting an error 'An unexpected error has occurred. Please seek technical support. ' It is occurring for a specific table version only. It is table AJM01 on version 5.2.0 in dev. If I try compare the live version 5.0 to the historical version 4.0 the error appears and the application freezes.  There are no source details appearing for version 4.0.  If I load and publish later versions and run the comparison it works.

**Comment by damiancosmoschapman** [comment] 2022-09-21 08:40
This was due to corrupt data for AJM01. This is the cause of the error and is not a bug. The table data does not exist in the database for the table. I am not sure why or how this table data was removed. We should probably replace the pxstat.dev database with data from pxstat.live to start with a clean database for the next sprint.

**Comment by liamie** [comment] 2022-11-09 15:26
closed invalid

**Closed by liamie** 2022-11-09 15:26 UTC
Labels: bug, invalid
