### ISSUE TITLE
[BUG] User details not displayed for AD user

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#370] opened 2021-02-12 10:43 UTC
**Describe the bug**
In the Dashboard or Releases pages the User details for AD users are not displayed. It refers to them as type Local

**To Reproduce**
1. Go to 'Dashboard and select any section
2. Click on imported by section
3. Popup pages appears with user details 

**Expected behavior**
Correct user details are displayed

**Comment by neilfromcork** [comment] 2021-02-12 11:05
Looks ok when I run PxStat.Security.Account_API.Read - @damienderoistecso can you check?

**Comment by damienderoistecso** [comment] 2021-02-12 11:37
@neilfromcork I think issue is that "PxStat.Security.Account_API.Read" is returning an array of one object and I am expecting just an object. It should be the same as "PxStat.Security.Account_API.ReadCurrent" which returns a single object

**Comment by damienderoistecso** [comment] 2021-02-12 12:20
Fixed in dev

@JohnPCarroll ready for test

**Comment by damienderoistecso** [comment] 2021-02-12 12:23
Duplicate of #324 

@JohnPCarroll I'm marking this as a duplicate of #324 as this was a result of the open access changes. If you come across any bugs in this testing to do with users/access/permissions can you log against #324 as they are more than likely because of that rather than a bug that was always there

**Closed by damienderoistecso** 2021-02-12 12:23 UTC
Labels: bug, fixed
