### ISSUE TITLE
[BUG]  Unexpected Error When  trying to view data

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#155] opened 2020-07-01 13:46 UTC
I'm getting an unexpected error when clicking the view data button on any live table from data in dev 
![image](https://user-images.githubusercontent.com/55874862/86251259-8a288580-bba9-11ea-9d38-2fee2efcb27b.png)

![image](https://user-images.githubusercontent.com/55874862/86250956-2b630c00-bba9-11ea-88bb-3e904fa81913.png)

Also when I try view data a table in the release section it just hangs on the bars for loading.

**Comment by liamie** [comment] 2020-07-02 12:08
Unexpected error cleared now from live/data view . Still hangs in releases view data will try that again in a couple of days incase just a background issue with refactoring/build

**Comment by damienderoistecso** [comment] 2020-07-20 09:26
Duplicate of #165

**Closed by damienderoistecso** 2020-07-20 09:26 UTC
Labels: bug, fixed, tested
